version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev_bot
    env_file: ".env"
    restart: always
    environment:
      - API_HOST=host.docker.internal
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:29092
    volumes:
      - ./src:/app/src
